name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      composer-cache-key: ${{ steps.composer-cache.outputs.key }}
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
        working-directory: ./symfony

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV
        working-directory: ./symfony

      - name: Cache Composer dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('symfony/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ vars.PHP_VERSION }}'
          extensions: mbstring, xml, ctype, iconv, intl
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-scripts
        working-directory: ./symfony

  quality-control:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV
        working-directory: ./symfony

      - name: Restore Composer cache
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: ${{ needs.build.outputs.composer-cache-key }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ vars.PHP_VERSION }}'
          extensions: mbstring, xml, ctype, iconv, intl
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-scripts
        working-directory: ./symfony

      - name: Run QC tools
        run: |
          cp .env.example .env
          ./vendor/bin/phpcs
          ./vendor/bin/phpstan analyze
          ./vendor/bin/php-cs-fixer fix --dry-run
        working-directory: ./symfony

  testing:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV
        working-directory: ./symfony

      - name: Restore Composer cache
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: ${{ needs.build.outputs.composer-cache-key }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ vars.PHP_VERSION }}'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_pgsql
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-scripts
        working-directory: ./symfony

      - name: Run PHPUnit
        env:
          DATABASE_URL: "postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.POSTGRES_DB }}?serverVersion=16&charset=utf8"
        run: |
          cp .env.example .env
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:schema:create
          ./vendor/bin/phpunit
        working-directory: ./symfony
